[workspace]
resolver = "2"

members = [
    "vhost-device-gpio",
    "vhost-device-i2c",
    "vhost-device-rng",
    "vhost-device-scsi",
    "vhost-device-scmi",
    "vhost-device-vsock",
    "vhost-device-input",
]

[env]
pkg-config = "/home/leoy/Dev1/orko/libgpiod/install/lib/pkgconfig/"
